In [5]:
import numpy as np
a=np.random.randint(0,10,size=[3,3])  
print a
s = a[[1,2]]
print s.shape
print np.argmax(a, axis=0)
from cs231n.classifiers import neural_net


[[6 1 3]
 [6 0 6]
 [3 5 2]]
(2, 3)
[0 2 1]


In [6]:
import numpy as np
import time
X = np.random.randn(200, 200)
Y = np.random.randn(200, 200)

def judge(x):
    if x>0:
        return 1.0
    return x
convert = np.frompyfunc(judge,1,1)
C = convert(Y).astype(int)
t1 = time.time()
r = X.dot(C)
t2 = time.time()
print t2-t1
Y[Y>0] = 1

t1 = time.time()
r = X.dot(Y)
t2 = time.time()
print t2-t1

print C.dtype
arr = np.array([3])
print arr.size
np.median(arr)
lrs = [1e-7, 5e-5]
for i in lrs:
    print i

0.000762939453125
0.000659227371216
int64
1
1e-07
5e-05


In [7]:
class Complex:
    def __init__(self, realpart, imagpart):
         self.r = realpart
         self.i = imagpart
c1 = Complex(1, 2)
c2 = None
c2 = c1
c2.r = 100
print c1.r, c2.r
c1.r = 101
print c1.r, c2.r



100 100
101 101
